apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-api
  labels:
    app: node-api
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: lbg-api
        image: gcr.io/lbg-training/ollie-node-app:jenkins-build-27
